### ISSUE TITLE
Quickstart for Devs

### ISSUE THREAD

**Issue by jdjkelly** [flexpa/sero#35]
This issue builds on #28 #31 #9 but incorporates some new ideas and is related to the 0.1.0 Launch milestone. Part of the goal of 0.1.0 is to have a first great dev documentation experience.

We are going to use Gitbook to create a "guide oriented" version of the reference manual (the old docs.sero.run will live at manual.sero.run or ref.sero.run as a reference manual built from the code whereas the new docs.sero.run will be the guide/gitbook written introduction to the project).

## Goal

**Completing this Issue means having written content for the sections listed below and addressing the additional tasks**. Some of the content (i.e. SMART on FHIR) has a dependency on Sero building support for that. Writing content will require, in general, ensuring that concepts are digestible with supporting information. The task here is to have written narrative that matches the quality of any code example. They re-enforce each other.

- [x] Installing Sero Speedrun (#43)
- User Guides
  - [x] Start a CDS Hooks API (#36), and (maybe) Start a SMART on FHIR App
  - [x] #69
- Example Projects
  - [x] #48
  - [x] #67
  - [x] TBD/other contributions 

This issue will also require:
- [x] Restructuring the `examples` directory so that each subfolder is a "complete" guide/code example whose folder name matches the name of the guide above (i.e. `examples/goodrx-cds-price-comparison`) - there shouldn't be anything left in `examples` root other than folders and these should roughly map 1 to 1 with the links above (start-a-cds-hooks-api etc)
- [x] Each example should have its own dependencies (i.e. npm init each subfolder, guides can even use something that's not javascript - each example/guide is isolated)
- [x] Each example should consume sero through npm instead of through a link to src - this will probably break some things because the published version doesn't 100% work correctly

## Dependencies
TBD

**Comment by mseckykoebel** [comment]
Marking #36 as done here. Code at `example/cds-hooks-api-guide` is all done, and supporting documentation has been written pending some edits.
