### ISSUE TITLE
Write the "Start a CDS Hooks API" guide

### ISSUE THREAD

**Issue by jdjkelly** [flexpa/sero#36]
As described in #35, we are going to write a guide called Start a CDS Hooks API.

The goal here to organize a "beginner to intermediate" tutorial from the examples we've been developing and to organize it into a single folder in the project and a page on the docs site. See also the detail in #35 about re-arranging the `example` folder.

Some food for thought:

- The example/guide should start with very simple - introduce how to make a Service, what is a Service anyways?
- Service should do as little as possible initially, patient-view - just echo back something like the current time, not even read patient data, but introduce the idea of returning Cards
- The next step of the guide should expose ideas in prefetch/context and use a slightly more complex example of using patient data/echoing patient data
- The next (last?) step should show an example with suggestions/actions?

Lastly, and this is true for the way I am writing the GoodRx example, I think the content in `examples/start-a-cds-hooks-api` should more or less contain each of the "steps" above in a separate file, and each file can have written notes as code comments. Then I would just aggregate all of those code comments and example snippets up into the written guide. I think that's just probably an easy approach.

Let's use this issue to organize the work to date/immediate future around. @mseckykoebel thoughts on this at #35?

**Comment by jdjkelly** [comment]
I'll grant access to gitbook.com for the writing portion (I have it syncing to github but not comfortable writing the commits there yet)

**Comment by mseckykoebel** [comment]
I like the idea of setting out on building something from the start and building the pieces of it/concepts towards something (like the nextjs tutorial has you build a blog step by step and at each step they add something on). Similar to what you were saying about "graduating."  

I will be thinking more about what specific example this would encapsulate - I developed my Alzheimers example a bit but I can look into some examples that could mimic a more common example in the real world.

**Comment by mseckykoebel** [comment]
Referenced issues: #49, #52, #53. Once these are all done, they will be fleshed out and referenced in the gitbook docs page.

**Comment by mseckykoebel** [comment]
Closing the above issues and listing out the separate steps and deliverables here:

- [x] Write "Getting started - mirror current time with CDS hooks" example
- [x] Write "Prefetch and context" example
- [ ] Write "Links and advanced service with FHIR" example

Each of these examples will ship in its own folder in the `cds-hooks-api-guide` folder. Each example is its own server and can be run directly.

**Comment by mseckykoebel** [comment]
Update: onto the final example. v1 documentation is available for 5/6 pages at [https://docs.sero.run/overview/guides/cds-hooks](https://docs.sero.run/overview/guides/cds-hooks).
