### ISSUE TITLE
Write "Links and advanced service with FHIR" example

### ISSUE THREAD

**Issue by mseckykoebel** [flexpa/sero#53]
Similar to #48, #49, and #52. Towards #36. In this example, we introduce links, and more advanced FHIR queries in prefetch (mainly different kinds of observations).

- [ ] Isolate the links and advanced service with FHIR example.
- [ ] Write a descriptive guide to go along with it.
    - [ ]  Have to expose the local dev server so CDS hooks can see it
- [ ] Successfully modularize the library (required in order to finish isolation task) for consumption in a default ES6/Node LTS project + a default TypeScript/Node LTS project.

**Comment by jdjkelly** [comment]
@mseckykoebel looking at this and the other similar ones - #48, #49, #52 - do we still need them vs just tracking #36?

**Comment by mseckykoebel** [comment]
I made these originally to list under #35 (under the good Rx example in the guides section), but because they are all a part of #36 I could delete these and set up PR's that track #36, as these are all examples but not standalone like goodRx. I'll clean up tonight - have a better understanding of the doc. structure now.
