### ISSUE TITLE
Participate in Connectathon 28

### ISSUE THREAD

**Issue by jdjkelly** [flexpa/sero#75]
[Connectathon 28 is happening Sep 13-15](https://confluence.hl7.org/display/FHIR/2021+-+09+Connectathon+28)

Goal is to participate in the [CDS Hooks WG](https://confluence.hl7.org/display/FHIR/2021-09+CDS+Hooks?src=contextnavpagetreemode) and be able to say that Epic or Cerner or some other large company successfully consumed our service

- [x] @TH33765 to register 2 tickets 
- [x] Sign up (and also use as a way to anticipate participation) for the CDS Hooks WG at https://bit.ly/cds-hooks-connectathon-tracking
- [x] Subscribe to the Zulip stream https://chat.fhir.org/#narrow/stream/179159-cds-hooks
- [x] Participate in any CDS Hooks WG specific kickoff calls (happening Sep 9 now)
- [x] Plan to have a CDS Service live during the connectathon that we test according to the track details @mseckykoebel - broadly something to do (#77)
- [x] Update docs.sero.run with any documentation changes to existing docs from changes to the lib created by participation @mseckykoebel 
- [x] We will need to finish to participate successfully https://github.com/Automate-Medical/sero/issues/7 (this is assigned to me)

Separately, we should treat this Connectathon as an opportunity to launch Sero

- [x] Have a Substack post ready to go about it
- [x] Say that we are participating with Epic, Cerner, etc on different plaforms
- [x] Maybe a video we try to push
- [x] Do a version 0.1.0 release and complete the 0.1.0 Launch milestone

**Comment by jdjkelly** [comment]
Additionally, there are other working group tracks that use CDS Hooks, and poking around the material might reveal some interesting opportunities. For example: https://confluence.hl7.org/display/FHIR/2021-09+Da+Vinci+Provider+Access+and+Burden+Reduction

**Comment by jdjkelly** [comment]
Kickoff is scheduled: 

> Track Kick-off/Orientation on Thursday, Sep 9th @ 12pm Eastern

**Comment by mseckykoebel** [comment]
Made a note about point number 6 in slack, but holding off on updating the goodRx documentation until after the connectathon, as it involves re-recording Josh's demo video and a lot of other changes that we might find easier to revert back.
