### ISSUE TITLE
Docker failure in GoodRx Example

### ISSUE THREAD

**Issue by jdjkelly** [flexpa/sero#87]
@XinhaoGeUW is going to document the failure message and investigate further

**Comment by XinhaoGeUW** [comment]
In [goodrx-cds-price-comparison](https://github.com/Automate-Medical/sero/tree/master/example/goodrx-cds-price-comparison), after running two commands locally:
docker build -t goodrx-cds:latest .
docker run -p 8080:8080 -ti --rm goodrx-cds:latest
 
It gives an error: 
Error: Cannot find module '/app/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by XinhaoGeUW** [comment]
Solved.
When I running the example locally (not cloning), I didn't add the correct "files" and "outDis" attributes in the tsconfig.json file. 
Thus the "docker build" command did not build the module successfully as expected. 
After adding the attributes, the "module not found" error is fixed.

**Comment by XinhaoGeUW** [comment]
BTW, if you clone the examples directly, it's recommended that you run the command before "docker build", which is
"npm i --save @sero.run/sero@latest". This may solve version issues.

**Comment by jdjkelly** [comment]
Whoops, I didn't mean to re-open this issue. This makes sense.
