### ISSUE TITLE
Node 16 LTS 

### ISSUE THREAD

**Issue by jdjkelly** [flexpa/sero#95]
On October 26th Node 16 becomes the active LTS, we should track this version.

Sero has a few places where we will need to upgrade the required node version but we shouldn't have any breakages.

- [x] Change package.json reference
- [x] Change references in Github actions
- [x] @types/node

**Comment by jdjkelly** [comment]
Can you switch to Node 16 and run `npm install` too? It should produce a diff

**Comment by mseckykoebel** [comment]
Yep just installed `16.1.1` doing right now.

**Comment by mseckykoebel** [comment]
Done

**Comment by jdjkelly** [comment]
Resolved fully now - slightly different approach, but we support 16 thru testing
